Repository nestjsx/nestjs-config, pull requests merged in 2019-01, with the labels that each got.

#58 Fixed issue with interface
  src/module/config.service.ts
Labels: bug

#59 Added basic info on modifyConfigName method
  README.md
Labels: documentation

#62 fix typo
  README.md
Labels: bug, documentation

#60 Standardize on single quotation marks
  README.md
Labels: documentation, enhancement
