Repository nestjsx/nestjs-config, pull requests merged in 2019-02, with the labels that each got.

#65 Added basic issue template
  .github/issue_template.md
Labels: documentation

#70 Updated dotenv type version
  package.json
  src/module/config.service.ts
  yarn.lock
Labels: bug

#74 Fixed npm repo option in package
  package.json
Labels: bug

#67 fix dependencies lock
  package-lock.json
Labels: bug, versioning

#75 Updated typescript
  package.json
  yarn.lock
Labels: enhancement

#77 Added missing resolveRootPath method to configmodule
  src/__tests__/config.module.spec.ts
  src/module/config.module.ts
Labels: bug
